export const UNAUTHORIZED_EXCEPTION =
  'UNAUTHORIZED_EXCEPTION';

export const FORBIDDEN_EXCEPTION = 'FORBIDDEN_EXCEPTION';

export const NOT_FOUND_EXCEPTION = 'NOT_FOUND_EXCEPTION';

export const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';

export const BAD_REQUEST_EXCEPTION =
  'BAD_REQUEST_EXCEPTION';
